@Library("mylib@main") _
import org.devops.*

// ========== 工具类初始化 ==========
def artifacts = new Artifacts()
def notified = new Notified()
def deploy = new Deploy()


// ========== 配置变量 ==========
def DEFAULT_USER_EMAIL = 'wangysh@ciicsh.com'

// ========== 应用变量 ==========
def app = ['project':'devops', 'appName':'devops03-maven-service', 'appType': 'maven', 'deployHosts': ['172.24.25.65', ], 'targetDir':'/opt', 'deployType': 'stand']

pipeline {
    agent { label "build"}

    options {
        skipDefaultCheckout true
        timestamps()
    }

    parameters {
        string 'releaseVersion'
    }

    stages{
        // stage("PullArtifacts"){
        //     steps{
        //         script{
        //             artifacts.PullRawArtifacts("${env.releaseVersion}", app.project, app.appName, app.appType)
        //         }
        //     }
        // }

        stage("Deploy"){
            steps{
                script{
                    deploy.DeployByAnsible(
                        deployHosts: app.deployHosts,
                        targetDir: app.targetDir,
                        appName: app.appName,
                        releaseVersion: env.releaseVersion,
                        deployType: app.deployType
                    )                      
                }
            }
        }

    }

    post {
        always{
            wrap([$class: 'BuildUser']) {
                script {
                    def causes = currentBuild.getBuildCauses()
                    env.triggerDescription = causes ? causes[0].shortDescription : "未知触发"

                    // 设置构建描述
                    currentBuild.description = """                           
                        Version: ${env.releaseVersion}
                    """.stripIndent().trim()
                    currentBuild.displayName = "#${env.BUILD_NUMBER} - ${env.triggerDescription}"
                
                    // 发送构建通知
                    env.USER_EMAIL = "${env.webhook_userEmail ?: env.BUILD_USER_EMAIL ?: params.PARAMS_USER_EMAIL}"
                    notified.SendEmail("${env.USER_EMAIL}")

                }
            }
        }        
    }
}


