@Library("mylib@main") _
import org.devops.*

// ========== 工具类初始化 ==========
def artifacts = new Artifacts()
def notified = new Notified()
def deploy = new Deploy()


// ========== 配置变量 ==========
def DEFAULT_USER_EMAIL = 'wangysh@ciicsh.com'

// ========== 应用变量 ==========
// def app = ['deployHosts': ['172.24.25.65'], 'project':'devops', 'appName':'devops03-maven-service', 'appType': 'maven', 'deployType': 'stand', 'targetDir':'/opt/app']
// def app = ['deployHosts': ['172.24.25.65'], 'project':'devops', 'appName':'devops03-maven-service', 'appType': 'maven', 'deployType': 'docker-compose', 'targetDir':'/opt/app2']
def apps = [
            ['deployHosts': ['172.24.25.65'], 'project':'devops', 'appName':'devops03-maven-service', 'appType': 'maven', 'deployType': 'k8s', , 'targetDir':'/opt/', 'appNs': 'devops', 'appKind': 'deployment']
        ]



pipeline {
    agent { label "build"}

    options {
        skipDefaultCheckout true
        timestamps()
    }

    parameters {
        string 'releaseVersion'
    }

    stages{
        // stage("PullArtifacts"){
        //     steps{
        //         script{
        //             artifacts.PullRawArtifacts("${env.releaseVersion}", app.project, app.appName, app.appType)
        //         }
        //     }
        // }

        stage("Deploy"){
            steps{
                script{
                    apps.each { app -> 
                        deploy.DeployByAnsible(
                            deployHosts: app.deployHosts,                        
                            project: app.project,
                            appName: app.appName,
                            deployType: app.deployType,
                            releaseVersion: env.releaseVersion,
                            targetDir: app.targetDir ?: '',
                            appNs: app.appNs ?: '',
                            appKind: app.appKind ?: ''
                        )  
                    }                    
                }
            }
        }

    }

    post {
        always{
            wrap([$class: 'BuildUser']) {
                script {
                    def causes = currentBuild.getBuildCauses()
                    env.triggerDescription = causes ? causes[0].shortDescription : "未知触发"

                    // 设置构建描述
                    currentBuild.description = """                           
                        Version: ${env.releaseVersion}
                    """.stripIndent().trim()
                    currentBuild.displayName = "#${env.BUILD_NUMBER} - ${env.triggerDescription}"
                
                    // 发送构建通知
                    env.USER_EMAIL = "${env.webhook_userEmail ?: env.BUILD_USER_EMAIL ?: params.PARAMS_USER_EMAIL}"
                    notified.SendEmail("${env.USER_EMAIL}")

                }
            }
        }        
    }
}


