@Library("mylib@main") _
import org.devops.*

// ========== 工具类初始化 ==========
def artifacts = new Artifacts()

// ========== 配置变量 ==========
def DEFAULT_USER_EMAIL = 'wangysh@ciicsh.com'

// ========== 应用变量 ==========
def app = ['project':'devops', 'appName':'devops03-maven-service', 'appType': 'maven']

pipeline {
    agent { label "build"}

    options {
        skipDefaultCheckout true
        timestamps()
    }

    parameters {
        string 'releaseVersion'
    }

    stages{
        stage("PullArtifacts"){
            steps{
                script{
                    artifacts.PullRawArtifacts("${env.releaseVersion}", app.project, app.appName, app.appType)
                }
            }
        }

        stage("DeployHost"){
            steps{
                script{
                    println("DeployHost")                       
                }
            }
        }

        stage("ServiceCtrl"){
            steps{
                script{
                    println("ServiceCtrl")                       
                }
            }
        }

        stage("HealthCheck"){
            steps{
                script{
                    println("HealthCheck")
                }
            }
        }
    }

    post {
        always{
            wrap([$class: 'BuildUser']) {
                script {
                    // 设置构建描述
                    currentBuild.description = """                           
                        version: ${env.releaseVersion}
                    """.stripIndent().trim()
                    // currentBuild.displayName = "#${env.BUILD_NUMBER} - Trigger by Jenkins"
                
                    // 发送构建通知
                    env.USER_EMAIL = "${env.webhook_userEmail ?: env.BUILD_USER_EMAIL ?: params.PARAMS_USER_EMAIL}"
                    notified.SendEmail("${env.USER_EMAIL}")

                }
            }
        }        
    }
}


